version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Your_password123
    volumes:
      - sql_data:/var/opt/mssql
    ports:
      - "1433:1433"
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    environment:
      AZURITE_ACCOUNTS: "devstoreaccount1:${AZURITE_KEY}"
    ports:
      - "10000:10000"
      - "10001:10001"
  funcapp:
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    environment:
      - KeyVault__Url=https://your-keyvault.vault.azure.net/
      - AZURE_STORAGE_CONNECTION_STRING=UseDevelopmentStorage=true
      - ConnectionStrings__Default=Server=sqlserver,1433;Database=appdb;User Id=sa;Password=Your_password123;Encrypt=False
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcollector:4317
    ports:
      - "7071:80"
    depends_on:
      - sqlserver
      - azurite
      - otelcollector
  otelcollector:
    image: mcr.microsoft.com/azuremonitor/opentelemetry-collector:latest
    environment:
      - AZURE_MONITOR_CONNECTION_STRING=${AZURE_MONITOR_CONNECTION_STRING}
    ports:
      - "4317:4317"
volumes:
  sql_data:
