name: Release Desktop
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        run: echo "Publishing desktop app..."
      - name: Upload
        run: echo "Uploading installer..."
