name: Test and Build
on:
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore ServiceStarterKit.sln
      - name: Lint
        run: dotnet format --no-restore --verify-no-changes
      - name: Build
        run: dotnet build --no-restore ServiceStarterKit.sln
      - name: Test
        run: dotnet test --no-build --verbosity normal ServiceStarterKit.sln
